apiVersion: v1
kind: Secret
metadata:
  name: infra-stack-lab-secrets
  namespace: infra-stack-lab
  labels:
    app.kubernetes.io/name: infra-stack-lab
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DATABASE_URL: 'your-database-url'
  ARCJET_KEY: 'your-arcjet-key'
